version: 2

sources:
  - name: jaffle_shop
    database: dbtworkshop
    schema: jaffle_shop
    tables:
      - name: customers
        columns:
          - name: id
            description: The unique identifier for the customer
            tests:
              - not_null
              - unique
          - name: first_name
            description: The first name of the customer
            tests:
              - not_null
          - name: last_name
            description: The last name of the customer
            tests:
              - not_null
      - name: orders
        columns:
          - name: id
            description: The unique identifier for the order
            tests:
              - not_null
              - unique
          - name: user_id
            description: The identifier of the user who placed the order
            tests:
              - not_null
          - name: order_date
            description: The date the order was placed
            tests:
              - not_null
          - name: status
            description: The status of the order
            tests:
              - not_null
          - name: _etl_loaded_at
            description: The timestamp when the order record was loaded
            tests:
              - not_null
  - name: stripe
    database: dbtworkshop
    schema: stripe
    description: ""
    tables:
      - name: payment
        description: ""
        columns:
          - name: id
            description: ""
          - name: orderid
            description: ""
          - name: paymentmethod
            description: ""
          - name: status
            description: ""
          - name: amount
            description: ""
          - name: created
            description: ""
          - name: _batched_at
            description: ""

  - name: tpch
    database: dbtworkshop
    schema: tpch_s3_test
    loader: s3
  
    tables:
      - name: customer
        external:
          location: "s3://dbt-data-lake-819052087103/dbtworkshopdata/customer"        # amazon s3 path prefix
          row_format: serde 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
          table_properties: "('skip.header.line.count'='1')"
        columns:
          - name: c_custkey
            data_type: varchar(255)
          - name: c_name
            data_type: varchar(255)
          - name: c_address
            data_type: varchar(255)
          - name: c_nationkey
            data_type: varchar(255)
          - name: c_phone
            data_type: varchar(255)         
          - name: c_acctbal
            data_type: varchar(255)
          - name: c_mktsegment
            data_type: varchar(255)
          - name: c_comment
            data_type: varchar(255) 